-------------CHEF C00002會M00001哪幾道菜色
SELECT * FROM MENU_DISH WHERE EXISTS (
    SELECT 1 FROM CHEF_DISH WHERE CHEF_ID = 'C00002' AND MENU_DISH.DISH_ID = CHEF_DISH.DISH_ID
) AND MENU_ID = 'M00001';


-------------會M00001套餐部份菜色的廚師
SELECT * FROM CHEF_DISH WHERE EXISTS (
    SELECT 1 FROM MENU_DISH WHERE MENU_ID = 'M00001' AND MENU_DISH.DISH_ID = CHEF_DISH.DISH_ID
) ORDER BY CHEF_ID;
-------------會XXXXX套餐的廚師
SELECT CHEF_ID FROM CHEF_DISH WHERE EXISTS (
    SELECT 1 FROM MENU_DISH WHERE MENU_ID = 'M00003' AND MENU_DISH.DISH_ID = CHEF_DISH.DISH_ID
) GROUP BY CHEF_ID
HAVING COUNT(DISH_ID) = ( SELECT COUNT(*) FROM MENU_DISH WHERE MENU_ID = 'M00003' );
-------------XXXXX廚師會哪幾個套餐
-------------尚未成功
SELECT MENU_ID, COUNT(DISH_ID)
FROM MENU_DISH
WHERE EXISTS (
    SELECT 1 FROM CHEF_DISH WHERE CHEF_ID='C00002' AND CHEF_DISH.DISH_ID = MENU_DISH.DISH_ID
) GROUP BY MENU_ID;




-------------廚師擅長菜色和套餐擁有的菜色JOIN
SELECT *
FROM CHEF_DISH
JOIN MENU_DISH ON CHEF_DISH.DISH_ID = MENU_DISH.DISH_ID;




